// Fix: Provide concrete definitions for SPEAKING_TOPICS and CRITERIA.
// Using 'as const' helps TypeScript infer more specific types, which resolves
// type errors in components that consume these constants.

export const SPEAKING_TOPICS = {
  en: {
    "New Speaking Tasks": [
      "Freestyle (Talk about any topic you want)",
      "Introduce yourself and your country.",
      "Talk about famous places or tourist attractions in your country.",
      "Describe what people can do in your capital city.",
      "Talk about national days and how people celebrate them.",
      "Say what you can or can’t do in English or at school.",
      "Make a short dialogue between two international students talking about their schools.",
      "Describe your typical school day.",
      "Talk about how you study and revise for exams.",
      "Explain your learning style (How do you learn best?).",
      "Compare your weekday and weekend routines.",
      "Role-play: Two classmates talking about how they prepare for a test.",
      "Talk about your best friend’s study habits.",
      "Describe yourself or a close friend.",
      "Talk about someone you admire and why.",
      "Describe a celebrity’s appearance and character.",
      "Say how physical and personal traits can affect friendships.",
      "Compare two people using adjectives (taller, more cheerful, etc.).",
      "Express opinions: “He is too shy to speak in public,” “She is brave enough to try new things.”",
      "Talk about your family members and their jobs.",
      "Describe what your parents do in their daily work life.",
      "Ask and answer about different jobs (“Where does he work?” “He works in a hospital.”).",
      "Describe your dream job and why you want it.",
      "Compare jobs in terms of difficulty and responsibility.",
      "Role-play: Interview a relative about their job.",
      "Describe your house or room.",
      "Talk about your neighborhood and what you like about it.",
      "Explain what you and your family are doing at home now.",
      "Give directions or describe how to get from your home to school.",
      "Talk about your favorite room and why.",
      "Role-play: A friend visits your home; you give a short house tour.",
      "Compare life in the city and in the countryside.",
      "Talk about traditional foods in your city or country.",
      "Describe a local food festival or event.",
      "Talk about what you usually eat at home vs. in restaurants.",
      "Say what kind of food you prefer and why.",
      "Discuss healthy vs. unhealthy eating habits.",
      "Talk about your favorite animal and its habitat.",
      "Describe an endangered species and explain why it is in danger.",
      "Give advice on how to protect nature (“We should recycle more.”).",
      "Talk about how people can reduce pollution.",
      "Discuss why it’s important to protect animals.",
      "Role-play: An interview with an environmental activist.",
      "Talk about your favorite film and describe its genre.",
      "Make predictions about life in the future.",
      "Discuss how technology will change education or jobs.",
      "Say what you will or won’t do in the future.",
      "Give advice for a better future (“People should use clean energy.”).",
      "Role-play: A film critic and a viewer discussing a new movie."
    ],
    "IELTS Speaking Topics": [
      "Talk about your city. Where is it? What kind of place is it?",
      "Talk about your education. What are you studying? Why did you choose this major?",
      "Describe a website where you bought something. What did you buy, why did you buy it, and were you satisfied?",
      "What are the advantages and disadvantages of online shopping?",
      "Describe a person in your family you admire. Who are they, what are they like, and why do you admire them?",
      "Is it better to have a few close friends or many friends?",
      "Describe an interesting journey you've taken.",
      "How has technology changed the way people communicate?"
    ],
    "TOEFL Speaking Topics": [
      "\"It is more important for a city to have beautiful design than to be functional.\" Do you agree or disagree, and why?",
      "Some people prefer to work for a company, while others prefer to have their own business. Which do you prefer, and why?",
      "Should schools require students to wear uniforms? Why or why not?",
      "Is it more important to learn about the past, or to focus on the present and the future? Why?"
    ]
  },
  tr: {
    "Yeni Konuşma Görevleri": [
      "Serbest Konuşma (İstediğiniz bir konu hakkında konuşun)",
      "Kendini ve ülkeni tanıt.",
      "Ülkendeki ünlü yerlerden veya turistik mekanlardan bahset.",
      "Başkentinde insanların neler yapabileceğini anlat.",
      "Milli bayramlardan ve insanların bunları nasıl kutladığından bahset.",
      "İngilizce'de veya okulda neler yapabildiğini veya yapamadığını söyle.",
      "Okulları hakkında konuşan iki uluslararası öğrenci arasında kısa bir diyalog oluştur.",
      "Tipik bir okul gününü anlat.",
      "Sınavlara nasıl çalıştığını ve tekrar yaptığını anlat.",
      "Öğrenme stilini açıkla (En iyi nasıl öğrenirsin?).",
      "Hafta içi ve hafta sonu rutinlerini karşılaştır.",
      "Rol yapma: İki sınıf arkadaşı bir sınava nasıl hazırlandıkları hakkında konuşuyor.",
      "En iyi arkadaşının ders çalışma alışkanlıklarından bahset.",
      "Kendini veya yakın bir arkadaşını tarif et.",
      "Hayranlık duyduğun birinden ve nedeninden bahset.",
      "Bir ünlünün dış görünüşünü ve karakterini tarif et.",
      "Fiziksel ve kişisel özelliklerin arkadaşlıkları nasıl etkileyebileceğini söyle.",
      "Sıfatlar kullanarak iki kişiyi karşılaştır (daha uzun, daha neşeli vb.).",
      "Fikir belirt: “Topluluk önünde konuşmak için çok utangaç,” “Yeni şeyler deneyecek kadar cesur.”",
      "Aile üyelerinden ve mesleklerinden bahset.",
      "Ailenin günlük iş hayatlarında ne yaptığını anlat.",
      "Farklı meslekler hakkında soru sor ve cevapla (“Nerede çalışıyor?” “Bir hastanede çalışıyor.”).",
      "Hayalindeki işi ve neden istediğini anlat.",
      "İşleri zorluk ve sorumluluk açısından karşılaştır.",
      "Rol yapma: Bir akrabanla işi hakkında röportaj yap.",
      "Evini veya odanı tarif et.",
      "Mahallenden ve orada neyi sevdiğinden bahset.",
      "Şu anda evde sen ve ailen ne yapıyorsunuz, anlat.",
      "Evden okula nasıl gidileceğini tarif et veya yol tarifi ver.",
      "En sevdiğin odandan ve nedeninden bahset.",
      "Rol yapma: Bir arkadaşın evini ziyaret ediyor; kısa bir ev turu yap.",
      "Şehir ve kırsal yaşamı karşılaştır.",
      "Şehrindeki veya ülkendeki geleneksel yiyeceklerden bahset.",
      "Yerel bir yemek festivalini veya etkinliğini tarif et.",
      "Genellikle evde ve restoranlarda ne yediğinden bahset.",
      "Ne tür yiyecekleri tercih ettiğini ve nedenini söyle.",
      "Sağlıklı ve sağlıksız yeme alışkanlıklarını tartış.",
      "En sevdiğin hayvandan ve yaşam alanından bahset.",
      "Nesli tükenmekte olan bir türü tarif et ve neden tehlikede olduğunu açıkla.",
      "Doğayı nasıl koruyacağımız konusunda tavsiyelerde bulun (“Daha fazla geri dönüşüm yapmalıyız.”).",
      "İnsanların kirliliği nasıl azaltabileceğinden bahset.",
      "Hayvanları korumanın neden önemli olduğunu tartış.",
      "Rol yapma: Bir çevre aktivisti ile röportaj.",
      "En sevdiğin filmden ve türünden bahset.",
      "Gelecekteki yaşam hakkında tahminlerde bulun.",
      "Teknolojinin eğitimi veya işleri nasıl değiştireceğini tartış.",
      "Gelecekte ne yapacağını veya yapmayacağını söyle.",
      "Daha iyi bir gelecek için tavsiyelerde bulun (“İnsanlar temiz enerji kullanmalı.”).",
      "Rol yapma: Bir film eleştirmeni ve bir izleyici yeni bir filmi tartışıyor."
    ],
    "IELTS Konuşma Konuları": [
      "Şehrinden bahset. Nerede? Nasıl bir yer?",
      "Eğitiminden bahset. Ne okuyorsun? Neden bu bölümü seçtin?",
      "Bir şey satın aldığın bir web sitesini tanımla. Ne satın aldın, neden aldın, memnun kaldın mı?",
      "Online alışverişin avantajları ve dezavantajları nelerdir?",
      "Ailende hayranlık duyduğun bir kişiyi tanımla. Kimdir, nasıldır, neden hayranlık duyuyorsun?",
      "Az sayıda yakın arkadaş mı, çok sayıda arkadaş mı daha iyidir?",
      "İlginç bir yolculuğunu anlat.",
      "Teknoloji insanların iletişim biçimini nasıl değiştirdi?"
    ],
    "TOEFL Konuşma Konuları": [
      "“Bir şehrin güzel tasarıma sahip olması, işlevsel olmasından daha önemlidir.” Katılıyor musun, neden?",
      "Bazı insanlar bir şirkette çalışmayı, bazıları ise kendi işini yapmayı tercih eder. Sen hangisini tercih edersin, neden?",
      "Okullar öğrencilerin üniforma giymesini zorunlu tutmalı mı? Neden?",
      "Geçmiş hakkında bilgi edinmek mi, yoksa bugüne ve geleceğe odaklanmak mı daha önemlidir? Neden?"
    ]
  }
} as const;

export const CRITERIA = {
  en: [
    { key: 'rapport' },
    { key: 'organisation' },
    { key: 'delivery' },
    { key: 'languageUse' },
    { key: 'creativity' },
  ],
  tr: [
    { key: 'rapport' },
    { key: 'organisation' },
    { key: 'delivery' },
    { key: 'languageUse' },
    { key: 'creativity' },
  ],
} as const;